# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7d91b4e0ac2587f0b3dd762c51a9e7c3d04ca47204b237c0d9e1d3679aa8386057a48c30da96c9b4643ce89439cca389508671af123c970d51c92d424498318c

test:
  secret_key_base: 0f72bf6c3f8d8ef30f732afdfb4938dced40db48ca4464792a98c20bf44adc68bdde004e9eebe6317c1006f9afb683e4d68fdd036860b2a75a8d250cf57052dd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
